// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeckee7jFHssrzcc3VFS01gCA_5umRViA',
    appId: '1:423693521060:android:91f96f2f14a447a02e1631',
    messagingSenderId: '423693521060',
    projectId: 'gistyet',
    storageBucket: 'gistyet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd_fuodplXN9OTPkdo7EUbET7QjIGJ5JA',
    appId: '1:423693521060:ios:7ff8931f3e33dba82e1631',
    messagingSenderId: '423693521060',
    projectId: 'gistyet',
    storageBucket: 'gistyet.appspot.com',
    androidClientId: '423693521060-gn4ku0g15qmhmlmbh0nf0fkg4se5j3m8.apps.googleusercontent.com',
    iosClientId: '423693521060-mh69fjgp1lhto4dg2an92ftf2skt9bvh.apps.googleusercontent.com',
    iosBundleId: 'com.nutmeup.provider',
  );
}
